url: "https://kyl6092.github.io"
baseurl: "/KYL-Code-Ground"
title: KYL-Code-Ground
email: kuoyu6092@gmail.com
description: >-
  My coding experiences and projects.
github_username: kyl6092 
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-feed
timezone: Asia/Taipei

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
